sudo: required
dist: trusty

language: haxe

haxe:
  - "3.2.1"
  - "3.4.2"
  # - development
  
# https://github.com/travis-ci/travis-ci/issues/7754#issuecomment-301223128
# matrix:
#   allow_failures:
#     - haxe: development
    
install:
  - haxelib git tink_io https://github.com/haxetink/tink_io pure
  - haxelib git tink_cli https://github.com/haxetink/tink_cli pure
  - haxelib git tink_macro https://github.com/haxetink/tink_macro
  - haxelib git travix https://github.com/back2dos/travix tink_cli && pushd . && cd $(haxelib config)travix/git && haxe build-neko.hxml && popd
  - haxelib run travix install

script:
  - haxelib run travix interp
  - haxelib run travix neko
  - haxelib run travix python
  - haxelib run travix node
  # - haxelib run travix flash
  - haxelib run travix java
  - haxelib run travix cpp
  - haxelib run travix cs
  - haxelib run travix php

env:
  secure: dhVtIkMcUYAyAK92oEzBiuHE2uH9MQ46PD8zdKnnky9WiH54x/Y167Wt1NvUhFxhNzfu44VpI5d1ngnSV5pwum+E/RfoJNoqIsRsy1dL/vnTwyBdGDwbBJc/RDqXYUQnF8okR3JBZKmr9FLXTl5DMKOP+mJE1IF6GLijTDR4pf8=

jobs:
  include:
    - stage: deploy
      os: linux
      haxe: "3.4.2"
      script: skip
      after_success: haxelib run travix release
